/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.8
 * Generated at: 2018-06-24 08:14:17 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<title>Fortress Quiz Manager</title>\r\n");
      out.write("<meta content=\"width=device-width, initial-scale=1.0\" name=\"viewport\">\r\n");
      out.write("<meta content=\"\" name=\"keywords\">\r\n");
      out.write("<meta content=\"\" name=\"description\">\r\n");
      out.write("\r\n");
      out.write("<!-- Favicons -->\r\n");
      out.write("<link href=\"resources/img/favicon.png\" rel=\"icon\">\r\n");
      out.write("<!-- <link href=\"resources/img/apple-touch-icon.png\" rel=\"apple-touch-icon\"> -->\r\n");
      out.write("\r\n");
      out.write("<!-- Google Fonts -->\r\n");
      out.write("<link\r\n");
      out.write("\thref=\"https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,700,700i|Montserrat:300,400,500,700\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Libraries CSS Files -->\r\n");
      out.write("<!-- <link href=\"resources/lib/font-awesome/css/font-awesome.min.css\" rel=\"stylesheet\"> -->\r\n");
      out.write("<link href=\"webjars/font-awesome/4.7.0/css/font-awesome.min.css\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("<link href=\"resources/lib/animate/animate.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"resources/lib/ionicons/css/ionicons.min.css\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("<link href=\"resources/lib/owlcarousel/assets/owl.carousel.min.css\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("<link href=\"resources/lib/lightbox/css/lightbox.min.css\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<!-- Main Stylesheet File -->\r\n");
      out.write("<link href=\"resources/css/style.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<!-- Bootstrap CSS File -->\r\n");
      out.write("<link href=\"webjars/bootstrap/4.1.1/css/bootstrap.min.css\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<!--==========================\r\n");
      out.write("    Header\r\n");
      out.write("  ============================-->\r\n");
      out.write("\t<header id=\"header\">\r\n");
      out.write("\t\t<div class=\"container-fluid\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div id=\"logo\" class=\"pull-left\">\r\n");
      out.write("\t\t\t\t<h1>\r\n");
      out.write("\t\t\t\t\t<a href=\"#\" class=\"scrollto\">QuizManager</a>\r\n");
      out.write("\t\t\t\t</h1>\r\n");
      out.write("\t\t\t\t<!-- Uncomment below if you prefer to use an image logo -->\r\n");
      out.write("\t\t\t\t<!-- <a href=\"#intro\"><img src=\"img/logo.png\" alt=\"\" title=\"\" /></a>-->\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- <nav id=\"nav-menu-container\">\r\n");
      out.write("        <ul class=\"nav-menu\">\r\n");
      out.write("          <li class=\"menu-active\"><a href=\"#intro\">Home</a></li>\r\n");
      out.write("          <li class=\"menu-has-children\"><a href=\"\">Management</a>\r\n");
      out.write("            <ul>\r\n");
      out.write("              <li><a href=\"#\">Questions</a></li>\r\n");
      out.write("              <li><a href=\"#\">MCQ Choices</a></li>\r\n");
      out.write("              <li><a href=\"#\">Students</a></li>\r\n");
      out.write("              <li><a href=\"#\">Answers</a></li>\r\n");
      out.write("              <li><a href=\"#\">Exams</a></li>\r\n");
      out.write("              <li><a href=\"#\">MCQ Answers</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("          </li>\r\n");
      out.write("          <li><a href=\"#team\">Student</a></li>\r\n");
      out.write("          <li class=\"menu-has-children\"><a href=\"\">Profile</a>\r\n");
      out.write("            <ul>\r\n");
      out.write("              <li><a href=\"#\">Settings</a></li>\r\n");
      out.write("              <li><a href=\"#\">Change Password</a></li>\r\n");
      out.write("              <li><a href=\"#\">Logout</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("          </li>\r\n");
      out.write("          <li><a href=\"#contact\">Contact</a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("      </nav> -->\r\n");
      out.write("\t\t\t<!-- #nav-menu-container -->\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</header>\r\n");
      out.write("\t<!-- #header -->\r\n");
      out.write("\r\n");
      out.write("\t<!--==========================\r\n");
      out.write("    Intro Section\r\n");
      out.write("  ============================-->\r\n");
      out.write("\t<section id=\"intro\">\r\n");
      out.write("\t\t<div class=\"intro-container\">\r\n");
      out.write("\t\t\t<div id=\"introCarousel\" class=\"carousel  slide carousel-fade\"\r\n");
      out.write("\t\t\t\tdata-ride=\"carousel\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<ol class=\"carousel-indicators\"></ol>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"carousel-inner\" role=\"listbox\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"carousel-item active\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"carousel-background\">\r\n");
      out.write("\t\t\t\t\t\t\t<img src=\"resources/img/intro-carousel/1.png\" alt=\"\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"carousel-container\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"carousel-content\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h2>Manage Your Quizes</h2>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p>You are able to manage all the exams or quizes without\r\n");
      out.write("\t\t\t\t\t\t\t\t\tany difficulty</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<form action=\"index\" method=\"POST\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"submit\" value=\"Use the Application\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"btn-get-started scrollto\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"carousel-item\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"carousel-background\">\r\n");
      out.write("\t\t\t\t\t\t\t<img src=\"resources/img/intro-carousel/2.png\" alt=\"\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"carousel-container\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"carousel-content\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h2>Student Management</h2>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p>You can also manage your students and allow them to take\r\n");
      out.write("\t\t\t\t\t\t\t\t\tan exam when it is required and other functions.</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<form action=\"index\" method=\"POST\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<button class=\"btn-get-started scrollto\">Use the\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tApplication</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<a class=\"carousel-control-prev\" href=\"#introCarousel\" role=\"button\"\r\n");
      out.write("\t\t\t\t\tdata-slide=\"prev\"> <span\r\n");
      out.write("\t\t\t\t\tclass=\"carousel-control-prev-icon ion-chevron-left\"\r\n");
      out.write("\t\t\t\t\taria-hidden=\"true\"></span> <span class=\"sr-only\">Previous</span>\r\n");
      out.write("\t\t\t\t</a> <a class=\"carousel-control-next\" href=\"#introCarousel\"\r\n");
      out.write("\t\t\t\t\trole=\"button\" data-slide=\"next\"> <span\r\n");
      out.write("\t\t\t\t\tclass=\"carousel-control-next-icon ion-chevron-right\"\r\n");
      out.write("\t\t\t\t\taria-hidden=\"true\"></span> <span class=\"sr-only\">Next</span>\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</section>\r\n");
      out.write("\t<!-- #intro -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!-- JavaScript Libraries -->\r\n");
      out.write("\t<script src=\"resources/lib/jquery/jquery.min.js\"></script>\r\n");
      out.write("\t<script src=\"resources/lib/jquery/jquery-migrate.min.js\"></script>\r\n");
      out.write("\t<script src=\"resources/lib/bootstrap/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("\t<script src=\"resources/lib/easing/easing.min.js\"></script>\r\n");
      out.write("\t<script src=\"resources/lib/superfish/hoverIntent.js\"></script>\r\n");
      out.write("\t<script src=\"resources/lib/superfish/superfish.min.js\"></script>\r\n");
      out.write("\t<script src=\"resources/lib/wow/wow.min.js\"></script>\r\n");
      out.write("\t<script src=\"resources/lib/waypoints/waypoints.min.js\"></script>\r\n");
      out.write("\t<script src=\"resources/lib/counterup/counterup.min.js\"></script>\r\n");
      out.write("\t<script src=\"resources/lib/owlcarousel/owl.carousel.min.js\"></script>\r\n");
      out.write("\t<script src=\"resources/lib/isotope/isotope.pkgd.min.js\"></script>\r\n");
      out.write("\t<script src=\"resources/lib/lightbox/js/lightbox.min.js\"></script>\r\n");
      out.write("\t<script src=\"resources/lib/touchSwipe/jquery.touchSwipe.min.js\"></script>\r\n");
      out.write("\t<!-- Contact Form JavaScript File -->\r\n");
      out.write("\t<script src=\"resources/contactform/contactform.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t<!-- JavaScript plugins -->\r\n");
      out.write("\t<script src=\"resources/js/main.js\" type=\"text/javascript\"></script>\r\n");
      out.write("\t<script src=\"webjars/jquery/3.3.1-1/jquery.min.js\"></script>\r\n");
      out.write("\t<script src=\"webjars/bootstrap/4.1.1/js/bootstrap.min.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
